name: IRIS CI/CD Scanner

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
        default: 'latest'
        type: string

jobs:
  iris-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Create Settings file
        run: |
          # Create Settings file
          jsonContent=$(jq -n --arg projectId "${{ secrets.PROJECT_ID }}" --arg jwt "${{ secrets.IRIS_JWT }}" \
                        '{projectId: $projectId, jwt_auth: $jwt}')

          echo $jsonContent > iris.settings.json
      
      - name: Download IRIS Scanner CLI 
        run: | 
          curl -L -o iris-scanner-cli https://iris.codeeye.ai/assets/onprem/v2/iris-scanner-cli_1_3_10
          chmod +x iris-scanner-cli
          
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Scan 
        run: |
          releaseName=${{ inputs.release_name }}
          currentDirectory=$PWD
          ./iris-scanner-cli -s $currentDirectory -r $releaseName -verbose
